### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by jacohend** [alexbosworth/ln-service#100]
Running the grpc example returns this error:

```
const wallet = await lnService.getWalletInfo({lnd});
               ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:720:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11
```

Even if we remove the async example, running the callback example results in an undefined result object (We've verified we can hit the node with curl + tls/macaroon creds). 

Does anyone have a working grpc example?

**Comment by alexbosworth** [comment]
You can only run `await` methods inside of an async function

so a full example would look like:

```node
(async () => {
  const wallet = await lnService.getWalletInfo({lnd});

  console.log(wallet)
})()
```

**Comment by alexbosworth** [comment]
You can also use cbk style if you prefer, that would be

```node
lnService.getWalletInfo({lnd}, (err, wallet) => {
  console.log(err, wallet);
});
```

**Comment by jacohend** [comment]
@alexbosworth Thanks!
