### ISSUE TITLE
psbt issue after upgrade

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/ln-service#132]
I have upgraded my package.json dependency and am now running into this issue: 

```
  ● Test suite failed to run

    /functions/node_modules/psbt/psbts/create_psbt.js:3
    const {global} = require('./types');
           ^

    SyntaxError: Identifier 'global' has already been declared

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1295:14)
      at Object.<anonymous> (node_modules/psbt/psbts/index.js:2:20)
```

seems the last commit is related to psbt so I'm assuming it's related: https://github.com/alexbosworth/ln-service/commit/9eabb4bb01b6fd0b94d79ad1df55c033f7053d14

**Comment by alexbosworth** [comment]
I'll look into this

**Comment by alexbosworth** [comment]
Try with the latest version?

**Comment by nicolasburtey** [comment]
working, thanks.
