### ISSUE TITLE
Using btcpay server

### ISSUE THREAD

**Issue by Dolu89** [alexbosworth/ln-service#70]
I have some trouble to connect ln-service to my LND node (btcpay server + LND installed with lunanode setup)

```
E1210 21:57:50.399000000 15220 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: 14 UNAVAILABLE: Connect Failed
    at Object.exports.createStatusError (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\common.js:87:15)
    at ClientReadableStream._emitStatusIfDone (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client.js:235:26)
    at ClientReadableStream._receiveStatus (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client.js:213:8)
    at Object.onReceiveStatus (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client_interceptors.js:1256:15)
    at InterceptingListener._callNext (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client_interceptors.js:614:8)
    at C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client_interceptors.js:1019:24
```
I used version 16.0 before with a neutrino node (this one https://github.com/Dolu89/lnd-docker), it worked very good. But it doesn't work with my btcpay server (testnet)

**Comment by alexbosworth** [comment]
Is it using the standard LND or a fork of LND?

**Comment by Dolu89** [comment]
It's a fork https://github.com/btcpayserver/lnd

**Comment by alexbosworth** [comment]
Only the standard LND would be supported, I think what's going on is that their fork removes authenticated communication and that's why ln-service can't communicate, because it requires authenticated communication

**Comment by Dolu89** [comment]
Good to know... Thanks for your fast answer :)

**Comment by NicolasDorier** [comment]
@alexbosworth it makes no sense, at the transport layer there is no difference with base LND. My two commits on top of LND have nothing to do with it.

**Comment by NicolasDorier** [comment]
Ping @mandelmonkey I know you made it works already,

**Comment by Dolu89** [comment]
As @NicolasDorier said, I used browser certificate (downloaded in base64). Now, I have this message 
```
E1211 08:19:04.503000000  4072 ssl_transport_security.cc:628] Could not load any root certificate.
E1211 08:19:04.548000000  4072 ssl_transport_security.cc:1691] Cannot load server root certificates.
E1211 08:19:04.577000000  4072 security_connector.cc:1098] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1211 08:19:04.616000000  4072 secure_channel_create.cc:121] Failed to create secure subchannel for secure name 'btcpaytest.lightningbutton.network:443'
E1211 08:19:04.650000000  4072 secure_channel_create.cc:154] Failed to create subchannel arguments during subchannel creation.
```

I suppose it's better than before :) I will do some other try later. Thank you all

**Comment by alexbosworth** [comment]
If you're using a domain to connect, make sure you're using tlsextradomain as an option in lnd when generating the cert

**Comment by NicolasDorier** [comment]
Yes, 

```
E1211 08:19:04.503000000  4072 ssl_transport_security.cc:628] Could not load any root certificate.
E1211 08:19:04.548000000  4072 ssl_transport_security.cc:1691] Cannot load server root certificates
```
Those error are strange.  It means that `ssl_transport_security` can't use the openssl trust store to know if the certificate is valid. 

I expect this line to give you the same issue:
```bash
openssl s_client btcpay.example.com:443
```

@Dolu89 unsure about how to configure the openssl trust store.

Try

```
apt-get install ca-certificates
```

**Comment by Dolu89** [comment]
@NicolasDorier ca-certificates is alreay installed on the server

**Comment by NicolasDorier** [comment]
what does `openssl s_client btcpay.example.com:443` do?

**Comment by CarlosRoldanx** [comment]
Hey! I am here trying to achieve the same a @Dolu89 

I have tried both:

```
root@lnd:~# openssl s_client lnd.satoshis.games:443
unknown option lnd.satoshis.games:443
usage: s_client args
```
&
```
root@lnd:~# openssl s_client btcpay.example.com:443
unknown option btcpay.example.com:443
usage: s_client args
```

**Comment by NicolasDorier** [comment]
`openssl s_client -connect btcpay.lightning-store.jp:443`

**Comment by Dolu89** [comment]
I was not sure about some informations are private or not. I replaced them with X

```
CONNECTED(00000003)
depth=0 CN = letsencrypt-nginx-proxy-companion
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = letsencrypt-nginx-proxy-companion
verify return:1
---
Certificate chain
 0 s:/CN=letsencrypt-nginx-proxy-companion
   i:/CN=letsencrypt-nginx-proxy-companion
---
Server certificate
-----BEGIN CERTIFICATE-----
XXXXXX
-----END CERTIFICATE-----
subject=/CN=letsencrypt-nginx-proxy-companion
issuer=/CN=letsencrypt-nginx-proxy-companion
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2003 bytes and written 431 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: XXXXXXX
    Session-ID-ctx:
    Master-Key: XXXXXX
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1545051486
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
```

**Comment by NicolasDorier** [comment]
@Dolu89 `verify error:num=18:self signed certificate` your certificate is not a real certificate.

Have you your own domain name, properly configured the DNS and use it with btcpay?

**Comment by Dolu89** [comment]
@NicolasDorier Yes I have my own domain name. It's btcpaytest.lightningbutton.network for my testnet btcpay server. I used Lunanode wizard to setup my btcpaynode. 
I created A record in my DNS zone to setup the domain

**Comment by NicolasDorier** [comment]
Ok wait a sec, I found something strange. This might be btcpay issue here.

**Comment by NicolasDorier** [comment]
@Dolu89 @CarlosRoldanx @mandelmonkey can you update your servers? I found out the issue.

**Comment by Dolu89** [comment]
Doing openssl commande again 
```
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = btcpaytest.lightningbutton.network
verify return:1
.......
```

**Comment by Dolu89** [comment]
But still not work

```
E1217 14:59:26.155000000 12524 ssl_transport_security.cc:628] Could not load any root certificate.
E1217 14:59:26.172000000 12524 ssl_transport_security.cc:1691] Cannot load server root certificates.
E1217 14:59:26.214000000 12524 security_connector.cc:1098] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1217 14:59:26.296000000 12524 secure_channel_create.cc:121] Failed to create secure subchannel for secure name 'btcpaytest.lightningbutton.network:10009'
E1217 14:59:26.390000000 12524 secure_channel_create.cc:154] Failed to create subchannel arguments during subchannel creation.
```

**Comment by NicolasDorier** [comment]
why is it `btcpaytest.lightningbutton.network:10009`? it should be `btcpaytest.lightningbutton.network:443`

**Comment by Dolu89** [comment]
Same error with 443 :(

**Comment by NicolasDorier** [comment]
give me a simple repro project so I can test.

**Comment by Dolu89** [comment]
Clone this repo https://github.com/Dolu89/ln-service-btcpay
Change settings in index.js (with your btcpay server config)

```
npm install
set GRPC_SSL_CIPHER_SUITES=HIGH+ECDSA
node index.js
```

**Comment by NicolasDorier** [comment]
@Dolu89 this library does not seem to support using it without the `cert` parameter.
If you use BTCPay, it should not be set because the certificate is renewed every 3 months. 
So either:
1. ask to @alexbosworth to not require the certificate for trusted domains
2. add a piece of code to download the certificate from the URL (you can because it is SSL), format it correctly, and give it to the library
3. do not use this library, use `grpc` directly as documented by @mandelmonkey ([here](https://github.com/alexbosworth/ln-service/issues/70#issuecomment-446059183))

**Comment by NicolasDorier** [comment]
The problem is here: https://github.com/alexbosworth/ln-service/blob/master/lightning/lightning_daemon.js#L34

This library needlessly limit the use of gRPC with fixed and untrusted certifcate (the default of LND).
BTCPay use trusted certificate and renew them every 3 months.

**Comment by NicolasDorier** [comment]
@Dolu89 I made a PR on https://github.com/alexbosworth/ln-service/pull/71

**Comment by CarlosRoldanx** [comment]
Awesome @NicolasDorier 

It works 👍

**Comment by CarlosRoldanx** [comment]
Sorry, I was wrong. I thought I was receiving the lightning daemon correctly.. But I wasn't

**Comment by Dolu89** [comment]
I updated ln-service with the version 30 and the update of @NicolasDorier (updated directly from node_modules folder)

I still have the same error

```
E1217 19:49:37.087000000  2464 ssl_transport_security.cc:628] Could not load any root certificate.
E1217 19:49:37.116000000  2464 ssl_transport_security.cc:1691] Cannot load server root certificates.
E1217 19:49:37.145000000  2464 security_connector.cc:1098] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1217 19:49:37.187000000  2464 secure_channel_create.cc:121] Failed to create secure subchannel for secure name 'btcpaytest.lightningbutton.network:443'
E1217 19:49:37.228000000  2464 secure_channel_create.cc:154] Failed to create subchannel arguments during subchannel creation.
```

**Comment by Dolu89** [comment]
After analyse, I just realised @mandelmonkey doesn't provide any SSL cert... So I tried with the new version of ln-service and I got `[503, "FailedToConnectToDaemon"]`

**Comment by alexbosworth** [comment]
Seems ok to me

**Comment by Dolu89** [comment]
Is this new value (`ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256`) will work for everyone? Or just btcpayserver users? To know if I can do a PR with thses changes or if I have to do a fork

**Comment by alexbosworth** [comment]
Are you still passing the cert or you are leaving that blank?

**Comment by Dolu89** [comment]
I don't pass this property anymore

**Comment by alexbosworth** [comment]
OK how about a PR where the env var is only checked if you pass the cert?

**Comment by Dolu89** [comment]
Ok great :) I will do it tomorrow. Thank you for your help!

**Comment by NicolasDorier** [comment]
Just did one. Do you think it is possible to make `GRPC_SSL_CIPHER_SUITES` completely optional? Because then the day let's encrypt decide to change the ciphers, then it will break tons of apps depending on specific cipher suite.

**Comment by alexbosworth** [comment]
Sure, I did this check because missing the env var is a common issue for the default setup

**Comment by NicolasDorier** [comment]
@alexbosworth I think this variable is internally used by the gRPC library isn't it ? As far as I understand 
@Dolu89 still needed to set `ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256` ?

**Comment by alexbosworth** [comment]
It has to do with GRPC yes

**Comment by NicolasDorier** [comment]
And no way to remove this check at gRPC level?

**Comment by alexbosworth** [comment]
Not that I know of

**Comment by Dolu89** [comment]
I thought it worked, but after 1 minute of execution, I have this error (but it works really good for 1 minute. I got events from websocket)

```
D1218 08:41:32.485000000  4160 dns_resolver.cc:338] Using native dns resolver
D1218 08:41:33.960000000  4160 dns_resolver.cc:279] Start resolving.
I1218 08:41:35.372000000  4160 subchannel.cc:656] New connected subchannel at 000002211343ED70 for subchannel 0000022112E34780
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: 13 INTERNAL: Received RST_STREAM with error code 2
    at Object.exports.createStatusError (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\common.js:87:15)
    at ClientReadableStream._emitStatusIfDone (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client.js:235:26)
    at ClientReadableStream._receiveStatus (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client.js:213:8)
    at Object.onReceiveStatus (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client_interceptors.js:1256:15)
    at InterceptingListener._callNext (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client_interceptors.js:614:8)
    at C:\Users\Dolu\projets\lightningbutton\node_modules\grpc\src\client_interceptors.js:1019:24
Application crashed, make sure to kill all related running process, fix the issue and re-run the app
```

I'm searching solution for this error, but if someone of you guys already know this error, don't hesitate :)

**Comment by NicolasDorier** [comment]
might be NGINX which close the connection after 1 min, just reconnect. Your code must do that anyway in case the server go down a bit, you don't want to crash the clients.

**Comment by Dolu89** [comment]
@NicolasDorier Oh interesting. Thank you! I will try that

**Comment by NicolasDorier** [comment]
I just made https://github.com/alexbosworth/ln-service/pull/73 to facilitate a bit.
